// Generated by generate-song-manifest.cjs. Do not edit.
export interface SongEntry { readonly id: string; readonly title: string; readonly file: string }
export const SONGS: readonly SongEntry[] = [
  {
    "id": "greensleeves",
    "title": "Greensleeves",
    "file": "Greensleeves.mxl"
  },
  {
    "id": "liebestraum-no-3-in-a-major",
    "title": "Liebestraum No. 3 in A Major",
    "file": "Liebestraum_No._3_in_A_Major.mxl"
  },
  {
    "id": "wa-mozart-marche-turque-turkish-march-fingered",
    "title": "Mozart: Marche Turque Turkish March fingered",
    "file": "WA_Mozart_Marche_Turque_Turkish_March_fingered.mxl"
  }
];
