// Generated by generate-song-manifest.cjs from song-library.config.cjs. Do not edit.
export interface SongEntry { readonly id: string; readonly title: string; readonly file: string; readonly composer: string; readonly credit?: string; readonly difficulty: string; readonly playerPerformedMelody?: boolean; readonly defaultLookAhead: number }
export const SONGS: readonly SongEntry[] = [
  {
    "id": "twinkle-theme",
    "title": "Twinkle Twinkle Little Star",
    "file": "Twinkle_Theme.musicxml",
    "composer": "Wolfgang Amadeus Mozart",
    "credit": "arr. Solángel",
    "difficulty": "Beginner",
    "playerPerformedMelody": true,
    "defaultLookAhead": 5
  },
  {
    "id": "twinkle-variation-01",
    "title": "Twinkle — Variation I",
    "file": "Twinkle_Variation_01.musicxml",
    "composer": "Wolfgang Amadeus Mozart",
    "credit": "arr. Solángel",
    "difficulty": "Fucking Difficult",
    "playerPerformedMelody": true,
    "defaultLookAhead": 4
  },
  {
    "id": "greensleeves",
    "title": "Greensleeves",
    "file": "Greensleeves.mxl",
    "composer": "Traditional",
    "credit": "arr. Dominique Makowski",
    "difficulty": "Intermediate",
    "defaultLookAhead": 6
  },
  {
    "id": "wa-mozart-marche-turque-turkish-march-fingered",
    "title": "Turkish March",
    "file": "WA_Mozart_Marche_Turque_Turkish_March_fingered.mxl",
    "composer": "Wolfgang Amadeus Mozart",
    "difficulty": "Advanced",
    "defaultLookAhead": 6
  },
  {
    "id": "liebestraum-no-3-in-a-major",
    "title": "Liebestraum No. 3",
    "file": "Liebestraum_No._3_in_A_Major.mxl",
    "composer": "Franz Liszt",
    "difficulty": "Not rated",
    "defaultLookAhead": 6
  }
];
