// Generated by node src/app/piano/generate-demand-metadata.cjs. Do not edit.
import type { DemandMetrics } from './gameplay/piano-wpm';
import type { PianoMode } from './gameplay/piano-mode';

export const SONG_DEMAND: Readonly<Record<string, Readonly<Record<PianoMode, DemandMetrics>>>> = {
  "twinkle-theme": {
    "rhythm": {
      "attackCount": 98,
      "activeSpanSeconds": 47.5,
      "averageWpm": 24.757894736842104,
      "peakWpm": 26.4,
      "peakAttacks": 11
    },
    "eight-keys": {
      "attackCount": 98,
      "activeSpanSeconds": 47.5,
      "averageWpm": 24.757894736842104,
      "peakWpm": 26.4,
      "peakAttacks": 11
    },
    "word-concert": {
      "attackCount": 98,
      "activeSpanSeconds": 47.5,
      "averageWpm": 24.757894736842104,
      "peakWpm": 26.4,
      "peakAttacks": 11
    }
  },
  "twinkle-variation-01": {
    "rhythm": {
      "attackCount": 322,
      "activeSpanSeconds": 47.5,
      "averageWpm": 81.34736842105264,
      "peakWpm": 96,
      "peakAttacks": 40
    },
    "eight-keys": {
      "attackCount": 322,
      "activeSpanSeconds": 47.5,
      "averageWpm": 81.34736842105264,
      "peakWpm": 96,
      "peakAttacks": 40
    },
    "word-concert": {
      "attackCount": 322,
      "activeSpanSeconds": 47.5,
      "averageWpm": 81.34736842105264,
      "peakWpm": 96,
      "peakAttacks": 40
    }
  }
};
